defenseunicorns/uds-common

- renovate.json
`v` is getting stripped off incorrectly in https://github.com/defenseunicorns/uds-common-tasks/pull/7/files
> fix: version template for zarf action

- tasks/publish.yaml
Remove variables in publish so they can be overridden in other task files.
> fix: prevent publish vars from being blown away

- .github/actions/setup/action.yaml
- README.md
- renovate.json
- tasks/create.yaml
- tasks/deploy.yaml
- tasks/publish.yaml
Removes need for zarf on its own, switches to the incredible `uds zarf` instead.
> chore: switch to uds zarf

- config/renovate.json5
Opening to start a discussion, or just merge. On PRs across UDS things the entire uds group gets tagged as a reviewers and gets emails about these PRs and any updates. I think it makes sense to disable the addition of reviewers to cut through the notification noise. Codeowners would still be required to approve/merge things, but this helps limit the noise to just participants in a PR. The downside is things could get lost for longer, but I think with proper structure around the team to review the dependency dashboard this should be mitigated.
Sidenote: I believe this ends up getting added by our extension of `config:base` which might be something to consider dropping instead.
> chore: remove reviewers from renovate

- config/renovate.json5
This updates the common renovate rule for @ separated versions to be brew specific (since that is majority where it is used).
> chore: update @ renovate rule to be more brewey

- tasks/create.yaml
This simply changes ZARF_ARCHITECTURE to UDS_ARCH (open for discussion and will require sibling PRs to uds-core, uds-package-gitlab, and likely others.
> chore: change the architecture in zarf package create to use UDS_ARCH

- .github/actions/setup/action.yaml
- .gitignore
- README.md
- config/renovate.json5
- renovate.json
adding renovate config changes needed to keep k3d up to date and also adding a .gitignore
> ci: k3d updates to be included in renovate PRs

- tasks/create.yaml
- tasks/deploy.yaml
Fixes: https://github.com/defenseunicorns/uds-common/issues/54
<details><summary>cli command line options</summary>
<p>
```
➜  ~ uds create --help
Create a bundle from a given directory or the current directory
Usage:
uds create [DIRECTORY] [flags]
Aliases:
create, c
Flags:
-c, --confirm                       REQUIRED. Confirm the removal action to prevent accidental deletions
-h, --help                          help for create
-o, --output string                 Specify the output (an oci:// URL) for the created bundle
-k, --signing-key string            Path to private key file for signing bundles
-p, --signing-key-password string   Password to the private key file used for signing bundles
Global Flags:
-a, --architecture string   Architecture for UDS bundles and Zarf packages …
```
> fix: fix UDS path

- tasks/pull.yaml
This adds spoofing into common to work around issues with pulled releases for upgrades while release please is trying to act on them.
> chore: add the ability to spoof to common

- tasks/pull.yaml
This removes the dash from the spoof input...
> chore: fix spoof to not include a dash

- config/renovate.json5
Open to discussion on this - personally dislike using a schedule on the shared config. I think that could be done per-repo if people desire. I think it creates more confusion around why a certain update is not in a PR already.
> chore: remove schedule on renovate

- .github/actions/test/action.yaml
- .github/workflows/ci-docs-shim.yaml
- .github/workflows/lint.yaml
- .github/workflows/tag-release.yaml
- .github/workflows/test-deploy.yaml
- bundle/uds-config.yaml
- config/renovate.json5
- renovate.json
- tasks.yaml
- tasks/create.yaml
- tasks/deploy.yaml
- tasks/publish.yaml
- tasks/setup.yaml
This adds upgrade testing to the workflows here to catch workflow issues earlier.
> chore: add upgrade tests to common

- config/renovate.json5
tested here: https://github.com/Racer159/uds-common/pull/11
> chore: fix renovate env var rule overmatching

- tasks/deploy.yaml
This pulls the specific package and bundle names and versions when running deploy tasks - this prevents errors when running uds tasks locally with older or different packages in place:
> chore: pull the current bundle and package names when deploying

- tasks/setup.yaml
Adds a mattermostid attribute on the create-doug-user so doug can log in to mattermost.
Updates uds version to 0.21.1 to get slim-dev working again.
> chore: give doug a mattermostid attribute and update uds version

- docs/uds-package-practices.md
This adds a note clarifying that UDS Packages must be capable of operating offline.
> chore: add an airgap note to UDS Package Practices (clarity is kindness)

- config/renovate.json5
Context is mostly included in the linked issue. TLDR - helm-values uses `docker` versioning so this aligns the two places we reference images.
Closes https://github.com/defenseunicorns/uds-common/issues/127
> fix: update renovate config to use docker versioning for zarf images

- .github/workflows/tag-release.yaml
swap out reference for `release-please-action` from the archived `google-github-actions` location to the new `googleapis` location.
> ci: update ref to release-please to new location

- .github/actions/debug-output/action.yaml
- .github/actions/save-logs/action.yaml
- .github/workflows/tag-release.yaml
- .github/workflows/test-deploy.yaml
This pulls in the debug and log actions from `uds-core` that give more debugging power to CI runs.
> chore: pull debug / log actions from uds-core

- config/renovate.json5
resolves #140 
I'm not using uds-common's renovate config directly, I BORROWED some of the regex and was getting warnings/errors with oci helm charts in zarf packages because renovate's regex managers would match it for helm datasource first before doing docker datasource for oci helm charts.
Renovate issue & repo:
https://github.com/defenseunicorns/narwhal-delivery-zarf-package-eks-addons/issues/6
Specifically testing on branch `renovate-is-hard` 👆 
Renovate config used:
https://github.com/defenseunicorns/narwhal-delivery-zarf-package-eks-addons/blob/main/renovate.json5#L4-L6
Fixed regex manager:
https://github.com/defenseunicorns/narwhal-delivery-renovate-config/blob/main/zarfPackageGenericMatching.json5#L74-L101
Renovate logs from zarf package with oci helm chart that was throwing an …
> fix: renovate incorrectly matching oci helm charts for helm datasources

- .github/actions/debug-output/action.yaml
This adds `|| echo "failed"` to the debug log action to continue in the event of failures looking things up - i.e. if pepr hasn't installed yet and there is no package CRD.
> chore: allow debug logs to continue through failure

- .github/actions/setup/action.yaml
Upgrade uds-cli to v0.11.2 because of an issue pulling image layers with v0.11.1
> chore: upgrade uds cli-cli to v0.11.2

- config/renovate.json5
This adds an image override to the renovate config (useful for `###ZARF_REGISTRY###` Helm values).
> feat: add an image override to the renovate config

- config/renovate.json5
This allow `ADD` commands in Dockerfiles to be renovated. See screenshot for proof that it is working. Here is the related package PR: https://github.com/defenseunicorns/uds-package-mattermost/pull/99
> chore: add dockerfile `ADD` support

- .github/workflows/commitlint.yaml
This fixes the permissions on the common `commitlint` workflow (to allow it to run on private / internal repos while we develop new things)
> chore: fix commitlint workflow permissions

- config/renovate.json5
This adds a version regex to the renovate for Zarf packages to match UDS package versioning schemes (as well as other semantic versions) - tested here:
- https://github.com/Racer159/uds-common/blob/d13629f5177feaf4257f8dcc5b6ea4a509077966/config/renovate.json5#L232C44-L234C129
- https://github.com/Racer159/uds-package-sonarqube/pull/17
> chore: fix version matching for UDS packages

- .github/workflows/ci-docs-shim.yaml
- .github/workflows/test-deploy.yaml
- config/renovate.json5
Based on https://github.com/renovatebot/renovate/discussions/22347 this should be password - failed typo/conflict fix.
Also filters out common renovate changes from the CI (using docs shim).
> fix: renovate typo token/password

- tasks/publish.yaml
This PR adds more specific package selection logic to allow for publishing auxiliary packages (i.e. mattermost-plugins) and also helping to ensure that other dep packages don't get picked up for publish.
> chore: refine package selection logic for publishing

- tasks/setup.yaml
This PR introduces the ability to automatically assign the Doug user to a specific Keycloak group during the `create-doug-user` task. This is achieved through the use of an environment variable, KEYCLOAK_GROUP, which specifies the group path.
Example Usage:
Running the following command creates the Doug user and assigns them to the Admin group, which is nested under the parent UDS Core group:
`uds run setup:create-doug-user --set KEYCLOAK_GROUP="/UDS Core/Admin"`
Behavioral Changes:
If KEYCLOAK_GROUP is not set: The Doug user is created without any group assignment, adhering to the existing behavior.
If KEYCLOAK_GROUP is set to a valid group: The Doug user is created and assigned to the specified group. In the example above, Doug would be added to the Admin group under UDS Core.
If …
> feat: add KEYCLOAK_GROUP var for create-doug-user task

- tasks/lint.yaml
Version 1.29.0 introduced something with the ignore filepaths. If using v1.28.0 or earlier you get the error `invalid config: ignore should contain file patterns`.
Anchors, in use in at least the uds-package-mattermost repo are not recognized in v1.29.0, hence setting v1.30.0 as the minimum allowed version.
As the code stood, having say version 1.26.0 installed satisfied the `pip install yamllint` command but `uds run lint:yaml` failed frustrating this end user.
> fix: mandate yamllint at least 1.30.0 to guarantee features in use

- .github/workflows/test-deploy.yaml
- .github/workflows/test.yaml
- tasks/upgrade.yaml
This adds an input to allow dependency commands to run in the cloned repo prior to bundle create as needed in some repos (i.e. something needing `uds run dependencies:create`)
> fix: allow dependent bundle commands to be run on upgrade tests

- .github/workflows/callable-publish.yaml
- .github/workflows/callable-test.yaml
adds -${{ runner.arch }} to the save-artifacts to ensure uniqueness under scenarios where the called workflows match except for architecture
> fix: add runner.arch to upload-artifacts name

- .github/workflows/callable-publish.yaml
- .github/workflows/callable-test.yaml
- tasks.yaml
remove with.assessment_results: /tmp/oscal-assessment-results.yaml in oscal task calls
> fix!: remove with.assessment_results from oscal tasks

- config/renovate.json5
We currently have a confusing combination of renovate options:
- `"rebaseWhen": "conflicted",`: Only rebases if a PR has conflicts
- `"rebaseStalePrs": true`: Sets `rebaseWhen` to `behind-base-branch` overriding ^
Imo it makes more sense to be less aggressive with rebasing in the base config and allow individual repos to override this. If this PR is not accepted as it stands we should still resolve the confusion around these two options (align them).
> chore: disable stale PR rebasing for renovate

- tasks/badge.yaml
To get the correct count of pods with the istio-proxy sidecar, I modified the jq command to output just one line per matching pod.
Fixes #281
> fix: modified jq command

- tasks/lint.yaml
Adds a short script to add `-ignore` flags for each line in gitignore that is not a comment/empty.
Caveat to this: `addlicense` does not behave exactly the same as `.gitignore`, for example a`folder` in the gitignore file will ignore that entire folder. With the addlicense command it must be `folder/**`. May necessitate some changes
> chore: have addlicense ignore gitignored files

- .github/actions/test-flavor/action.yaml
- .github/workflows/callable-test.yaml
- tasks/upgrade.yaml
This fixes the upgrade tests for private repos by no longer requiring auth
> fix: upgrade test not cloning in private repos

- tasks/lint.yaml
Adds a check for the `addlicense` binary before running the `license` and `fix-license` tasks
> chore: adds check for addlicense

- tasks/lint.yaml
Was getting a random `=1.30.0` file when running lint:deps locally.
> fix: lint:deps producing unwanted file

- .github/actions/test-flavor/action.yaml
- templates/test.yml
Don't fail if the tag doesn't have a zarf.yaml when doing upgrade flavor check.
> fix: don't fail if `zarf.yaml` not found in tag

- .github/actions/test-flavor/action.yaml
- templates/test.yml
Allows alternate paths for the check flavor zarf.yaml
> feat: allow alternate paths for the check flavor zarf.yaml

- templates/publish.yml
When you have escaped double quotes in a bash variable bash does some weird single quote things that the command actually ran looks like this
```
--set 'FLAVOR="upstream"'
```
which breaks our stuff
Fix is to switch to a bash array for keeping track of everything:
```
ARGS=(
--set FLAVOR="$[[ inputs.flavor ]]"
--set VERSION="$(uds-releaser show $[[ inputs.flavor ]] --version-only)"
)
ARGS+=(--set TARGET_REPO="$[[ inputs.target-repo ]]")
```
> fix: gitlab publish being broken due to bash weirdness

- templates/publish.yml
Part of the gitlab publish template was assuming the flavor would be in a variable called FLAVOR instead of using the defined input as the interface into this component.
> fix: use flavor from inputs instead of $FLAVOR variable

- tasks/upgrade.yaml
add git reset in upgrade-test directory on test-upgrade task for better local devx
> fix: add git reset in upgrade-test directory for better local devx

- docs/uds-packages/guide.md
> fix: update UDS Opeator link in guide.md

- tasks/setup.yaml
Allow `keycloak_group` input in `create-doug-user` task to add doug user to specified group, for example:
```yaml
- name: create-admin-doug
actions:
- task: setup:create-doug-user
with:
keycloak_group: /UDS Core/Admin
```
> feat: allow keycloak_group to be specified as input in create-doug-user task

- docs/uds-packages/guide.md
- docs/uds-packages/requirements/uds-package-requirements.md
- fix broken links in `docs/uds-packages/guide.md` and `docs/uds-packages/requirements/uds-package-requirements.md`.
- Change name of `UDS Marketplace Package Integration Guide` to `UDS Airgap App Store Package Integration Guide`
> chore: fix broken links and change name of package integration guide

- config/renovate.json5
- releaser.yaml
- tasks.yaml
- tasks/publish.yaml
- tasks/upgrade.yaml
This adds a renovate rule to handle `-uds.x` versions correctly when mixed with upstream versions.
> chore: add a renovate rule for handling uds versions from upstream ones

- templates/publish.yml
> feat: move mirror ci to publish step

- tasks/upgrade.yaml
This fixes an issue where flavors containing a dash break on upgrade.
Fixes: #373
> fix: flavors containing a dash will fail on the upgrade task

- tasks/utils.yaml
Task ran to what would be the publish command
```
uds run publish:package --set ENABLE_UDS_RELEASER="true" --set FLAVOR=upstream --set BASE_REPO=ghcr.io/uds-packages
uds zarf package publish ./zarf-package-nginx-amd64-1.27.3-uds.0.tar.zst oci://ghcr.io/uds-packages
uds run publish:package --set ENABLE_UDS_RELEASER="true" --set FLAVOR=unicorn --set BASE_REPO=ghcr.io/uds-packages
uds zarf package publish ./zarf-package-nginx-amd64-1.27.3-uds.0.tar.zst oci://ghcr.io/uds-packages/private
uds run publish:package --set ENABLE_UDS_RELEASER="true" --set FLAVOR=upstream
uds zarf package publish ./zarf-package-nginx-amd64-1.27.3-uds.0.tar.zst oci://ghcr.io/defenseunicorns/packages/uds
uds run publish:package --set ENABLE_UDS_RELEASER="true" --set FLAVOR=unicorn
uds zarf package publish …
```
> chore: add private back to other orgs and restrict teams

- templates/commitlint.yml
commitlint shouldn't run on draft MRs in GitLab
> feat: do not run commitlint on draft MRs

- tasks/actions.yaml
- templates/test.yml
Allows for setting useful flags like `--insecure` or `--uds-cache` as inputs in the include section of GitLab CI/CD.
> feat: expose UDS CLI flag options for GitLab test template

- tasks/lint.yaml
- tasks/upgrade.yaml
Certain packages (jenkins in particular) have changed versioning schemas, causing a default sort to pull the wrong version in CI. This adds a lightweight grep to ignore certain versions.
Validated on https://github.com/defenseunicorns/uds-package-jenkins/pull/146/commits/92c821d15df36a56f37ebcbdfd153b1289cb8d47
> fix: add ignored_version input for upgrades

- config/renovate.json5
> fix: update renovate config to support raw github references with/without 'refs/tags/' in the url

- .github/workflows/callable-publish.yaml
- .github/workflows/callable-scan.yaml
- .github/workflows/release.yaml
- tasks/README.md
- tasks/actions.yaml
- tasks/publish.yaml
- templates/publish.yml
switch all references from uds-releaser to uds-pk and use non deprecated cli commands
> chore: switch all references from uds-releaser to uds-pk and use non deprecated cli commands

- tasks/create.yaml
Adds a way to ignore a version in the republish workflow.
> feat: add ignored_version input to republish task

- tasks/README.md
- tasks/setup.yaml
This Pull Request introduces a few helper tasks for managing Keycloak
Relates to: https://github.com/defenseunicorns/uds-identity-config/issues/373
> feat: keycloak helper tasks

- .github/workflows/callable-publish.yaml
It appears that the recent addition of the `republish-package` task to the `tasks.yaml` file in the root of this repo has unintentionally caused `uds run package-publish` to be triggered in the release workflow on this repo - this fails because the task does not exist in this repo. This is currently [blocking](https://github.com/defenseunicorns/uds-common/actions/runs/14625947580/job/41037331338) the release workflow. 
This PR updates the regular expression for checking for the `publish-package` task to match exact matches only.
> fix: broken task reference in callable-publish workflow

- config/renovate.json5
Removes a match for v0-9 in several of the regex matchers. Worth noting that most of the regex testers already reflected NOT having this character match.
This is required for and should resolve https://github.com/defenseunicorns/uds-package-minio-operator/issues/46
> fix: remove v0-9 restrictions on renovate matches

- .github/workflows/callable-test.yaml
The previous PR that added authentication for `uds run` to overcome the GitHub rate-limiting on unauthenticated requests missed one location where the authentication is needed. This PR adds that additional auth setup command in callable test workflow
> fix: add additional auth setup in callable test workflow

- .gitignore
- templates/deploy.yml
- templates/publish.yml
- templates/test.yml
Need to be able to configure a different token to use for gitlab registry auth. In some cases the use of the job token isn't sufficient.
> feat: add gitlab registry auth config to gitlab templates

- .github/workflows/callable-scan.yaml
Renovate is failing to update branch due to an issue with the crane renovate comment in the callable-scan workflow. This fixes that comment.
> chore: fix crane renovate config in scan workflow

- tasks/lint.yaml
In multiple places, see [here](https://github.com/defenseunicorns/uds-registry/blob/3d8a80fe62b1638c73d4f867f5684fb25a449106/tasks/lint.yaml#L36-L46) and [here](https://github.com/defenseunicorns/uds-multicluster/blob/fdb4253e1da0b352fa11595cfdce982362bd9a9f/tasks/lint.yaml#L25-L32) we are working around the usual installation path for addlicense from being just `$GOPATH/bin` to being `$HOME/bin/go`. 
The former is standard in the [go world ](https://go.dev/wiki/GOPATH#gopath-variable) so I'm proposing we stop using this "hack" and just align with all the tooling :sweat_smile:
> chore: install addlicense to /home/maciej/workspace/unicorns/bin just like all the other go tools
