README.md, renovate.json
Downgrading uds-core in the docs because it wasn't actually upgraded.
=> fix: renovate for uds core

README.md, config/renovate.json5, renovate.json
This is a PR to hold a common renovate config for use across UDS (this will improve management of this file across repositories).
=> chore: add common renovate config

config/renovate.json5
This adds the npm regex from @mjnagel to the common renovate config
=> chore: add npm regex to common renovate config

tasks.yaml, tasks/create.yaml, tasks/deploy.yaml
resolves #24 
Tested create and deploy by emulating the common task in uds-capability-cert-manager:
`uds run deploy-pkg --set deploy_options="--components=deploy-custom-manifests --set cert_manager_manifests=examples/deploy-custom-manifests.yaml --set cert_manager_values=.github/ci-values/values-override.yaml"`
` uds run create-pkg --set flavor=upstream --set create_options="./test/"`
=> chore: update to actionable tasks

.github/workflows/pull_request.yaml
Testing to see if this is a viable workaround for release-please PRs.
=> chore: introduce a fix for release-please not firing on PR workflows

.github/workflows/commitlint.yaml
PR of quick change to your PR to avoid shell command injection. Following uds-core's example https://github.com/defenseunicorns/uds-core/blob/bf7c1d28e077cf52d4f765b50d7efb8ce5d60fff/.github/workflows/commitlint.yaml#L29
=> fix: use workflow env for pr.title

.github/actions/test/action.yaml, tasks/create.yaml, tasks/deploy.yaml, tasks/publish.yaml
Adds a publish task to publish dev versions of bundles for testing.
=> chore: add a publish job for dev bundles

.github/workflows/lint.yaml, .github/workflows/tag-release.yaml
This fixes my mistakes :disappointed:
=> chore: fix missing keys in setup actions

config/renovate.json5
tested here: https://github.com/Racer159/uds-common/pull/11
=> chore: fix the renovate config github digest pinning

manifests/uds-package.yaml, tasks.yaml, uds-package.yaml, values/common-values.yaml, zarf.yaml
This adds a UDSPackage CR to the `podinfo` package in this repo to make it more suitable for testing things in `uds-core`
=> chore: add a UDS package CR to make the package better for testing

config/renovate.json5
This fixes the extract version template for k3d.
=> chore: fix the extract version template for env vars

tasks/deploy.yaml, tasks/remove.yaml
This adds a common remove task and uses the vendored version of `yq` from Zarf
=> chore: add a common bundle remove task

.github/actions/playwright/action.yaml
This adds a playwright setup action for use in downstream repos.
=> chore: add a playwright setup action

config/renovate.json5
This adds two new GitHub renovate regexes to catch more things automatically
=> chore: add the second raw URL and releases URL for GitHub to renovate config

CODEOWNERS, CONTRIBUTING.md, LICENSE
This updates the `CODEOWNERS` file to protect some files but also open up more of the repository to others.
=> chore: update CODEOWNERS with more specific permissions

.github/actions/setup/action.yaml
Adds the chainctl setup/identity assumption to the setup action.
=> chore: add cgr identity assume to setup action

.github/actions/playwright/action.yaml
This adds an additional action to ensure playwright deps are installed as per: https://github.com/microsoft/playwright/issues/7249#issuecomment-1597663397
=> chore: add additional install step to playwright install

tasks/setup.yaml
update doug ci credential for new identity config req
=> fix!: update doug ci credential for new identity config req

config/renovate.json5
=> fix: renovate ghcr host docker type

values/registry1-values.yaml, values/unicorn-values.yaml, values/upstream-values.yaml, zarf.yaml
This reverts commit 688197cfcfdf2e14c222f82c59d27904fd1753bb.
=> revert: update uds common nginx package (#223)

config/renovate.json5
See https://docs.renovatebot.com/modules/manager/terraform/#terraform-vs-opentofu
=> chore(renovate): prefer opentofu registry for providers

README.md
This fixes the path to the release workflow in the README
=> chore: correct the release workflow path on README

docs/uds-packages/guide.md
=> fix: broken hyperlink in guide.md

tasks.yaml
=> fix: refactor top level tasks

.github/workflows/callable-publish.yaml, .github/workflows/callable-test.yaml
This fixes the workflow upload for test and publish reports
=> fix: test/publish workflow upload and default behavior

tasks/pull.yaml, tasks/upgrade.yaml
Make all Maru references local includes
=> chore: make all Maru references local includes

docs/uds-packages/requirements/uds-package-requirements.md
Intent to provide earlier look at -unicorn flavors. i.e. if available use it, if not request it. (another PR, will include guidelines around requesting images)
=> chore(badging): include unicorn flavor suggstion for bronze

docs/uds-packages/guide.md
=> docs: update core capabilities link

docs/uds-packages/requirements/uds-package-requirements.md
Changed the air-gapped verbiage to match the style we use elsewhere
...
=> chore: update uds-package-requirements.md

.github/workflows/callable-test.yaml
=> chore: add if to only run the clean runner task on ubuntu-latest

.yamllint, tasks/lint.yaml
This installs yamllint into a venv inside a repo to make it easier to use.
=> chore: make yamllint easier to run locally

.github/workflows/callable-publish.yaml, .github/workflows/callable-test.yaml, .github/workflows/common-checks.yaml, tasks.yaml, tasks/README.md, tasks/actions.yaml, tasks/lint.yaml
This improves task checks/linting and allows options to be passed to tests/publish tasks
=> chore: improve task checks/linting and allow more options on test/publish

.github/workflows/callable-publish.yaml, .github/workflows/callable-test.yaml
=> fix: timeout too short on test workflows - allow adjustment on test/publish

docs/uds-packages/development/common-workflows.md, tasks/actions.yaml, tasks/badge.yaml
This improves the uds-badge verification task and dependency installs for GH
=> chore: improve badge verification and dep installs

.github/workflows/callable-ci-docs-shim.yaml, .github/workflows/callable-commitlint.yaml, .github/workflows/callable-lint.yaml, .github/workflows/callable-publish.yaml, .github/workflows/ci-docs-shim.yaml, .github/workflows/common-checks.yaml, .github/workflows/test.yaml, README.md
=> chore: update workflow permissions

tasks/pull.yaml
=> fix: pull mv command to use latest version

docs/uds-packages/requirements/uds-package-requirements.md
Update CODEOWNERS guidance in badging requirements with updated CODEOWNERS in `uds-package-template`
=> chore: update uds-package-requirements with new CODEOWNERS reqs

tasks/actions.yaml, templates/publish.yml, templates/test.yml
=> feat: login to ghcr from gitlab for upgrade tests and avoiding rate limiting

config/renovate.json5
Check tests directories in renovate updates
=> fix: check tests directories in renovate updates

.github/workflows/callable-publish.yaml, tasks/publish.yaml
=> fix: quote conditional and add use chkpt false

tasks/upgrade.yaml
=> chore: fix the upgrade task

.github/workflows/callable-publish.yaml
=> chore: add debug output to callable-publish

config/renovate.json5
Adds regex matches (and tests) for `<!--` comments which are used in some markdowns.
=> chore: add support for markdown comments to renovate config

tasks/upgrade.yaml
This move command was failing on some operating systems, so check for file existing before trying to mv the file.
=> chore: fix mv command on upgrade tests

docs/uds-packages/requirements/uds-package-requirements.md
Fix dead link in UDS Package Requirements doc
Links pointed to non-existent docs.
=> fix: update uds-package-requirements.md

templates/README.md, templates/deploy.yml
Provide a GitLab CI/CD Deployment component for doing deployments of dev packages.
=> feat: create deploy template

tasks/actions.yaml
=> fix: hotfix uds-pk download

tasks/publish.yaml, templates/publish.yml
=> fix: show command is now under release

.github/workflows/callable-publish.yaml
=> fix: forgot outputs in github ref

.github/workflows/scan.yaml
=> fix: only run scan on prs

.github/workflows/callable-publish.yaml
=> fix: conditionals in release broke

docs/uds-packages/README.md, docs/uds-packages/development/common-workflows.md, docs/uds-packages/guide.md, docs/uds-packages/guidelines/metadata-guidelines.md, docs/uds-packages/guidelines/testing-guidelines.md, docs/uds-packages/requirements/uds-package-requirements.md
- Found and updated references from Airgap App Store -> Airgap Store. As well as a UDS Marketplace -> Airgap Store
- Updated a few dead links.
- Remove some archived links.
=> chore: remove app store references

config/renovate.json5
Adds file match support for *.tf in all the previous matchers that targetted more than yaml (yaml + json).
=> chore: update renovate matched to catch TF files

tasks/setup.yaml
=> fix: create-doug-user calls wrong task

.github/workflows/callable-test.yaml
=> fix: make verify badge in ci never cause a failure

.github/workflows/callable-scan.yaml
fix other crane renovate comment in scan workflow
=> chore: fix other crane renovate comment in scan workflow

config/renovate.json5
Removing hostType to test a fix for RF creds.
=> fix: renovate config

.github/workflows/callable-lint.yaml, .github/workflows/callable-publish.yaml, .github/workflows/callable-republish-package.yaml, .github/workflows/common-checks.yaml, tasks/lint.yaml
=> chore: update uds-cli

.github/workflows/callable-scan.yaml
=> fix: scan ci broken

docs/uds-packages/requirements/uds-package-requirements.md
Adds a note about how actions are supposed to be used in UDS Packages.
=> chore: clarify actions requirements for UDS packages

config/renovate.json5
Copy paste of the brew ones, just with `npx` instead. Added regex testers as well.
=> chore: add renovate support for npx @ versions

templates/lint.yml, templates/publish.yml
- Fixed a bug in the run license check logic in the lint template
- Changed how the args are constructed in the publish template to be compatible with sh.
...
=> chore: gitlab publish and lint template updates

.github/workflows/project-sync.yaml
=> chore(ci): add project sync workflow

docs/uds-packages/guidelines/metadata-guidelines.md
This improves guidance around the use of annotations within UDS Packages.
=> chore: expand UDS Package annotation guidance
